apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dummy-app
      namespace: dummy-app
  template:
    metadata:
      labels:
        name: dummy-app
        namespace: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: diogofilipedocker/dummy-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
