apiVersion: v1
kind: Service
metadata:
  name: dummy-app-service
  namespace: dummy-app
spec:
  ports:
    - nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: dummy-app
  type: LoadBalancer
